### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by brainwo** [Ukiyo-Server/tashikani#1]
I suggest to use more commonly use license(s) (e.g. MIT, Apache, or GPL). The Unlicense license isn't covering copyright notice, which might be a bad idea for this kind of project.
Kotoba bot for example is using the [MIT License](https://github.com/mistval/kotoba/blob/master/LICENSE). On other hand, Poketwo bot is using the [GPL License](https://github.com/poketwo/poketwo/blob/master/LICENSE). It could be helpful having the same license as Poketwo. The catch of using GPL License is that we should follow the Free Software [philosophy](https://www.fsf.org/about/what-is-free-software), which could be good or bad depending on a situation. All GPL-licensed derivatives must be released under the same license (GPL), meaning you can't release it under a closed source proprietary software using this license.

**Comment by idleboy4038** [comment]
> As a side note: from my understanding, the Unlicensed and other similar licenses are more mainly used for licensing templates and some unimportant projects.

I have added [GPL](https://github.com/Ukiyo-Server/tashikani/blob/main/LICENSE).

**Comment by brainwo** [comment]
> I have added [GPL](https://github.com/Ukiyo-Server/tashikani/blob/main/LICENSE).

Good choice
