### ISSUE TITLE
Meta: Kanji sources

### ISSUE THREAD

**Issue by brainwo** [Ukiyo-Server/tashikani#2]
Some sources I found:

[davidluzgouveia/kanji-data](https://github.com/davidluzgouveia/kanji-data): JSON sets from KANJIDIC, JLPT, and Wanikani (**MIT Licensed**, last update: Dec 29 2019)

**Comment by idleboy4038** [comment]
> Some sources I found:
> 
> [davidluzgouveia/kanji-data](https://github.com/davidluzgouveia/kanji-data): JSON sets from KANJIDIC, JLPT, and Wanikani (**MIT Licensed**, last update: Dec 29 2019)

This source is awesome, it is really useful.

**Comment by brainwo** [comment]
There's also this one repository that store JLPT kanji in txt format [sunillarsson/sunillarsson.github.io](https://github.com/sunillarsson/sunillarsson.github.io)

**Comment by brainwo** [comment]
Closing this issue in favor of #5
